/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

syntax = "proto2";

package android.os.statsd.npu;

import "frameworks/proto_logging/stats/atom_field_options.proto";
import "frameworks/proto_logging/stats/atoms.proto";
import "frameworks/proto_logging/stats/enums/npu/enums.proto";

extend Atom {
  optional NpuWorkEventOccurred npu_work_event_occurred = 1247
      [(module_name) = "npu"];
  optional NpuAppBlocked npu_app_blocked = 1269 [(module_name) = "npu"];
  optional NpuModelLoadRequested npu_model_load_requested = 1305 [(module_name) = "npu"];
  optional NpuModelLoadPolicyResponded npu_model_load_policy_responded = 1306 [(module_name) = "npu"];
  optional NpuModelLoadRequestCancelled npu_model_load_request_cancelled = 1307 [(module_name) = "npu"];
  optional NpuModelLoadStateChanged npu_model_load_state_changed = 1308 [(module_name) = "npu"];
}

/**
 * Logs when a NPU work event is received in NpuManager. These are
 * received when work is requested, starts, and ends, and is
 * debounced over a period of 50ms.
 *
 * Logged from:
 *     modules/NpuManager/service/java/com/android/server/npumanager/MetricsLogger.java
 *
 * Estimated Logging Rate:
 *     Entirely dependent on utilization of the NPU
 */
message NpuWorkEventOccurred {
  enum EventType {
    UNKNOWN = 0;
    REQUESTED = 1;
    STARTED = 2;
    ENDED = 3;
  }

  enum Reason {
    UNSPECIFIED = 0;
    INITIAL = 1;
    RESUMED = 2;
    CANCELLED_USER = 3;
    CANCELLED_SYSTEM = 4;
    PAUSED = 5;
    FAILED = 6;
    COMPLETED = 7;
  }

  optional int32 uid = 1 [(is_uid) = true];
  optional int32 debug_pid = 2;
  optional int32 original_uid = 3 [(is_uid) = true];
  optional int32 job_priority = 4;
  optional int32 effective_priority = 5;
  optional int64 timestamp_ms = 6;
  optional int32 device_number = 7;
  optional EventType type = 8;
  optional Reason reason = 9;
}

/**
 * Logged when NpuManager blocks an app from accessing the NPU. This is generally only
 * done once when the first request from an app is observed.
 *
 * Logged from:
 *     modules/NpuManager/service/java/com/android/server/npumanager/MetricsLogger.java
 *
 * Estimated Logging Rate:
 *     Depends on NPU utilization and the presence of misbehaving apps, but the upper
 *     bound would be one event per blocked app per boot.
 */
message NpuAppBlocked {
  optional int32 uid = 1 [(is_uid) = true];
}

/**
 * Logged when NpuManager receives an initial request to load a model from a client.

 * Logged from:
 *     modules/NpuManager/service/java/com/android/server/npumanager/MetricsLogger.java
 *
 * Estimated Logging Rate:
 *     Depends on NPU utilization.
 */
message NpuModelLoadRequested {
  // UID of the application making the request.
  optional int32 uid = 1 [(is_uid) = true];

  // ID for the model load request. IDs will be unique for each request.
  optional int32 request_id = 2;

  // Requested model size.
  optional android.npu.NpuModelSize model_size = 3;

  // Requested model priority.
  optional android.npu.NpuModelPriority model_priority = 4;
}

/**
 * Logged when the NpuManager responds to the model load request, letting the application know if
 * it can load the model.
 *
 * Logged from:
 *     modules/NpuManager/service/java/com/android/server/npumanager/MetricsLogger.java
 *
 * Estimated Logging Rate:
 *     Depends on NPU utilization.
 */
message NpuModelLoadPolicyResponded {
  optional int32 uid = 1 [(is_uid) = true];
  optional int32 request_id = 2;
  optional android.npu.NpuModelLoadStatus status = 3;
}

/**
 * Logged when a pending model load request is cancelled.
 *
 * Logged from:
 *     modules/NpuManager/service/java/com/android/server/npumanager/MetricsLogger.java
 *
 * Estimated Logging Rate:
 *     Depends on NPU utilization.
 */
message NpuModelLoadRequestCancelled {
  // UID of the client application owning the request.
  optional int32 uid = 1 [(is_uid) = true];

  // Client-provided ID for the model load request.
  optional int32 request_id = 2;
}

/**
 * Logged when a model has finished loading or unloading.
 *
 * Logged from:
 *     modules/NpuManager/service/java/com/android/server/npumanager/MetricsLogger.java
 *
 * Estimated Logging Rate:
 *     Depends on NPU utilization.
 */
message NpuModelLoadStateChanged {
  // UID of the client application that owned the model.
  optional int32 uid = 1 [(is_uid) = true];

  // Client-provided ID for the original load request.
  optional int32 request_id = 2;

  // The new state of the model.
  optional android.npu.NpuModelLoadState state = 3;
}
