/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

syntax = "proto2";

package com.google.android.wear.notification;

option java_multiple_files = true;
option java_outer_classname = "WearNotificationProtoEnums";

// Defines the specific point in the notification's journey in the watch
enum NotificationEvent {
  EVENT_UNSPECIFIED = 0;

  // Events logged by WearServices
  // Notification received in WearServices
  EVENT_RECEIVED_IN_WS = 1;
  // Notification filtered in WearServices, and not sent to UI
  EVENT_FILTERED_IN_WS = 2;
  // Notification sent to UI
  EVENT_SENT_TO_UI = 3;
  // Notification dismissed from source
  EVENT_DISMISSED_FROM_SOURCE = 4;
  // Notification dismissal sent to UI
  EVENT_SOURCE_DISMISSAL_SENT_TO_UI = 5;
  // Dismiss request received in WearServices
  EVENT_UI_DISMISSAL_RECEIVED_IN_WS = 6;
  // Dismiss request sent to source
  EVENT_UI_DISMISSAL_SENT_TO_SOURCE = 7;

  // Events logged by SysUI
  // Notification received in UI
  EVENT_RECEIVED_IN_UI = 8;
  // Notification filtered in UI
  EVENT_FILTERED_IN_UI = 9;
  // Notification alerted to user
  EVENT_ALERTED_TO_USER = 10;
  // User gazed and notification was processed
  EVENT_PROCESSED_BY_USER_GAZE = 11;
  // User did not gaze within window and timed out
  EVENT_USER_GAZE_TIMED_OUT = 19;
  // Heads Up Notification preview shown
  EVENT_HUN_PREVIEW_SHOWN = 20;
  // Glanceable skipped due to being muted
  EVENT_GLANCEABLE_SKIPPED_MUTED = 16;
  // Glanceable skipped due to sound and vibration off
  EVENT_GLANCEABLE_SKIPPED_SOUND_AND_VIBRATION_OFF = 17;
  // Glanceable skipped, showing HUN instead
  EVENT_GLANCEABLE_SKIPPED_SHOWING_HUN = 18;
  // Glanceable notification full view shown
  EVENT_GLANCEABLE_FULLVIEW_SHOWN = 12;
  // Heads Up Notification full view shown
  EVENT_HUN_FULLVIEW_SHOWN = 13;
  // Dismissed via Remote Action
  EVENT_REMOTE_ACTION_DISMISS_IN_UI = 14;
  // Notification removed from UI
  EVENT_REMOVED_IN_UI = 15;
}