/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

syntax = "proto2";

package com.google.android.clockwork.physicalux;

// Gesture Actions
enum GestureAction {
  ACTION_UNSPECIFIED = 0;
  ACTION_PRIMARY = 1;
  ACTION_DISMISS = 2;
  ACTION_WAKE = 3;
  ACTION_SLEEP = 4;
  ACTION_INVOKE_AI = 5;
  ACTION_SELECT = 6;
  ACTION_PAGE_FORWARD = 7;
  ACTION_PAGE_BACKWARD = 8;
}

// Raw Gestures
enum Gesture {
  GESTURE_UNSPECIFIED = 0;
  GESTURE_DOUBLE_PINCH = 1;
  GESTURE_WRIST_TURN = 2;
  GESTURE_SINGLE_PINCH = 3;
  GESTURE_PALM_UP_SINGLE_PINCH = 4;
  GESTURE_PALM_UP_DOUBLE_PINCH = 5;
  GESTURE_DOUBLE_WRIST_TURN = 6;
  GESTURE_BLOOM = 7;
  GESTURE_CLENCH = 8;
  GESTURE_PALM_UP_CLENCH = 9;
  GESTURE_PINCH_AND_FLICK_FORWARD = 10;
  GESTURE_PINCH_AND_FLICK_BACKWARD = 11;
  GESTURE_PINCH_AND_HOLD = 12;
  GESTURE_KNOCK = 13;
  GESTURE_DOUBLE_KNOCK = 14;
  GESTURE_SHAKE = 15;
  GESTURE_DOUBLE_SHAKE = 16;
}

// State of gesture detection
enum GestureDetectionState {
  STATE_UNSPECIFIED = 0;
  STATE_ACTIVE = 1;
  STATE_INACTIVE = 2;
}

// System Actions
enum SystemAction {
  SYSTEM_ACTION_UNSPECIFIED = 0;
  SYSTEM_ACTION_HOME = 1;
  SYSTEM_ACTION_BACK = 2;
  SYSTEM_ACTION_MEDIA = 3;
}

// Gesture Experience Events
enum GestureExperienceEvent {
  GESTURE_EXPERIENCE_EVENT_UNSPECIFIED = 0;
  GESTURE_EXPERIENCE_EVENT_HINT_SHOWN = 1;
  GESTURE_EXPERIENCE_EVENT_GESTURE_CONSUMED = 2;
}
