/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

syntax = "proto2";

package android.os.statsd.corenetworking.captiveportallogin;

import "frameworks/proto_logging/stats/atoms.proto";
import "frameworks/proto_logging/stats/atom_field_options.proto";
import "frameworks/proto_logging/stats/enums/corenetworking/captiveportallogin/enums.proto";

option java_package = "com.android.os.corenetworking.captiveportallogin";
option java_multiple_files = true;

extend Atom {
  optional CaptivePortalLoginReported captive_portal_login_reported = 1145
      [(module_name) = "captive_portal_login"];
}

/**
 * Logs Captive Portal Login events
 * Logged from:
 * packages/modules/CaptivePortalLogin/src/com/android/captiveportallogin/CaptivePortalLoginActivity.java
 */
message CaptivePortalLoginReported {
    // Record the UID of the browser app displaying the captive portal. If it's
    // the WebView, this field is absent.
    optional int32 uid = 1 [(is_uid) = true];

    // Record the captive portal result during the authentication.
    optional CaptivePortalResult portal_result = 2;

    // Record the specific reason why the WebView is triggered to display the
    // portal.
    optional CaptivePortalUsingWebViewReason reason = 3;

    // Record the captive portal login app events.
    optional CaptivePortalLoginAppEvent app_event = 4;

    // How long it take for captive portal login operation to complete in ms.
    optional int64 duration_ms = 5;
}
