/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

syntax = "proto2";

package android.app.wearsysui;

option java_multiple_files = true;
option java_outer_classname = "WearSysUiEnums";

// This enum depicts the text type of the content shown in Live Entry UI.
// Next ID: 3
enum LiveEntryTextType {
  // The data type is not specified.
  TEXT_TYPE_UNSPECIFIED = 0;
  // Simple, non-interactive text.
  TEXT_TYPE_STATIC = 1;
  // Dynamic Text like chronometer, such as a timer or stopwatch, media etc.
  TEXT_TYPE_DYNAMIC = 2;
}

// This enum depicts the type of content shown in Live Entry UI.
// Next ID: 3
enum LiveEntryContentType {
  // The entry type is not specified.
  CONTENT_TYPE_UNSPECIFIED = 0;
  // A live update, such as a ride-sharing ETA.
  CONTENT_TYPE_LIVE_UPDATE = 1;
  // An ongoing activity, such as a workout or timer.
  CONTENT_TYPE_ONGOING_ACTIVITY = 2;
}

// This enum depicts the type of content update in Live Entry UI.
// Next ID: 4
enum LiveEntryUpdateType {
  // The content update type is not specified.
  UPDATE_TYPE_UNSPECIFIED = 0;
  // The content is new in the UI.
  UPDATE_TYPE_NEW = 1;
  // The existing content is updated in the UI.
  UPDATE_TYPE_UPDATED = 2;
  // The content is removed from the UI.
  UPDATE_TYPE_REMOVED = 3;
}

/**
 * Live Update Setting option selected by the user
 * Next ID: 3
 */
enum LiveUpdateSettingOption {
  // Option unspecified
  OPTION_UNSPECIFIED = 0;
  // Icon and Text option selected
  OPTION_ICON_AND_TEXT = 1;
  // Icon only selected
  OPTION_ICON_ONLY = 2;
}

/**
 * The source from which Live Update Setting was entered
 * Next ID: 4
 */
enum LiveUpdateSettingEntrySource {
  // Entry unspecified
  ENTRY_SOURCE_UNSPECIFIED = 0;
  // Entered from WFCO UI
  ENTRY_SOURCE_WFCO = 1;
  // Entered from Notification Tray
  ENTRY_SOURCE_N10N_TRAY = 2;
  // Entered from Notification Full View
  ENTRY_SOURCE_N10N_FULL_VIEW = 3;
}

/**
 * Surface hosting the notification
 * Next ID: 6
*/
enum NotificationSurface {
  // Surface unspecified
  SURFACE_UNSPECIFIED = 0;
  // Notification tray surface containing chips
  SURFACE_TRAY_CHIP = 1;
  // Notification tray surface containing cards
  SURFACE_TRAY_CARD = 2;
  // Glanceable full view surface
  SURFACE_GLANCEABLE_FV = 3;
  // Heads up notification full view surface
  SURFACE_HUN_FV = 4;
  // Live update full view surface
  SURFACE_LIVE_UPDATE_FV = 5;
}

/**
 * State of the notification
 * Next ID: 3
 */
enum NotificationState {
  // State unspecified
  NOTIFICATION_STATE_UNSPECIFIED = 0;
  // Notification is expanded
  STATE_EXPANDED = 1;
  // Notification is collapsed
  STATE_COLLAPSED = 2;
}

/**
 * Enum representing the visibility state change.
 * Next ID: 3
 */
enum State {
  STATE_UNKNOWN = 0;
  VISIBLE = 1;
  HIDDEN = 2;
}

/**
 * Enum representing the type of icon shown on the screen.
 * Next ID: 17
 */
enum IconType {
  ICON_TYPE_UNSPECIFIED = 0;
  TYPE_BATTERY_LOW = 1;
  TYPE_BATTERY_SAVER = 2;
  TYPE_CHARGING = 3;
  TYPE_AIRPLANE_MODE = 4;
  TYPE_BEDTIME_MODE = 5;
  TYPE_DO_NOT_DISTURB = 6;
  TYPE_PHONE_DISCONNECTED = 7;
  TYPE_BLUETOOTH_OFF = 8;
  TYPE_LTE_DISCONNECTED = 9;
  TYPE_MICROPHONE = 10;
  TYPE_LOCATION = 11;
  TYPE_THEATER_MODE = 12;
  TYPE_WET_MODE = 13;
  TYPE_SCREEN_LOCK = 14;
  TYPE_THERMAL = 15;
  TYPE_UNTETHERED_SAFETY = 16;
}

/**
 * Enum to represent the reason why a notification was skipped while processing
 * (alerting or displaying).
 * Next ID: 14
 */
enum SkippedReason {
  SKIPPED_REASON_UNKNOWN = 0;
  // The notification was a group summary.
  SKIPPED_ALERT_REASON_GROUP_SUMMARY = 1;
  // The notification was considered stale.
  SKIPPED_ALERT_REASON_STALE_NOTIFICATION = 2;
  // Notification was filtered by a backend filter.
  SKIPPED_ALERT_REASON_FILTERED_BY_BACKEND_FILTER = 3;
  // The notification was filtered due to being hidden.
  SKIPPED_ALERT_REASON_HIDDEN = 4;
  // No notification was found in the queue to display.
  SKIPPED_DISPLAY_REASON_NOTIFICATION_NOT_FOUND = 5;
  // Glanceable was skipped because a HUN was shown instead.
  SKIPPED_DISPLAY_REASON_GLANCEABLE_SKIPPED_FOR_HUN = 6;
  // The notification was muted.
  SKIPPED_DISPLAY_REASON_NOTIFICATION_MUTED = 7;
  // Ringer and vibration were turned off.
  SKIPPED_DISPLAY_REASON_RINGER_AND_VIBRATION_OFF = 8;
  // HUN was skipped because the device was not interactive (V1 only).
  SKIPPED_DISPLAY_REASON_HUN_SKIPPED_NOT_INTERACTIVE = 9;
  // HUN was skipped because a new HUN window could not be added.
  SKIPPED_DISPLAY_REASON_HUN_SKIPPED_CANNOT_ADD_WINDOW = 10;
    // The HUN display was skipped because it was shown in tray
  SKIPPED_DISPLAY_REASON_SHOWN_IN_TRAY = 11;
  // The HUN display was skipped because keyboard is being shown
  SKIPPED_DISPLAY_REASON_KEYBOARD_SHOWING = 12;
  // The HUN display was skipped because top activity is immersive
  SKIPPED_DISPLAY_REASON_IMMERSIVE_TOP_ACTIVITY = 13;
}
