/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

syntax = "proto2";

package android.os.usb;

option java_multiple_files = true;
option java_outer_classname = "UsbStatsEnums";

// Enum for the state of Userspace AOA.
enum UserspaceAoaState {
  // Default value.
  USERSPACE_AOA_STATE_UNSPECIFIED = 0;
  // Userspace AOA implementation is DISABLED.
  USERSPACE_AOA_STATE_DISABLED = 1;
  // Userspace AOA implementation is ENABLED.
  USERSPACE_AOA_STATE_ENABLED = 2;
}

// Enum for the result of nativeOpenAccessoryControl().
enum OpenAccessoryControlResult {
    // Default value: nativeOpenAccessoryControl() was not called,
    // typically because a preceding check failed.
    UNSPECIFIED = 0;
    // nativeOpenAccessoryControl() failed to open FFS_ACCESSORY_EP0.
    OPEN_ACCESSORY_FAILED = 1;
    // nativeOpenAccessoryControl() failed to write descriptors
    WRITE_DESC_FAILED = 2;
    // nativeOpenAccessoryControl() failed to write accessory string
    WRITE_STRING_FAILED = 3;
    // nativeOpenAccessoryControl() failed dues to SELINUX permission.
    SELINUX_PERMISSION_FAILED = 4;
    // nativeOpenAccessoryControl() successfully opened Accessory Control.
    SUCCESS = 5;
}