/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

syntax = "proto2";

package android.os.statsd.authenticationpolicy;

import "frameworks/proto_logging/stats/atoms.proto";
import "frameworks/proto_logging/stats/atom_field_options.proto";

option java_package = "com.android.server.security.authenticationpolicy";
option java_multiple_files = true;

extend Atom {
  optional SecureLockDeviceStateChanged secure_lock_device_state_changed = 1192
      [(module_name) = "framework"];
}

/**
 * Reports when secure lock is enabled and disabled on a device, including information about how
 * secure lock device was disabled when relevant (i.e. manually vs. through two-factor
 * authentication).
 * Logged from:
 *   frameworks/base/services/core/java/com/android/server/authenticationpolicy/SecureLockDeviceService.java
 * Estimated Logging Rate:
 *   Peak: 2 times per device per day. | Avg: 1 time per device (total)
 */
message SecureLockDeviceStateChanged {
    enum SecureLockDeviceEventType {
        UNKNOWN = 0;
        DISABLED_MANUALLY = 1;
        DISABLED_TWO_FACTOR_AUTHENTICATION = 2;
        ENABLED = 3;
    }

    optional bool enabled = 1;
    optional SecureLockDeviceEventType event_type = 2;
}
