/*
 * Copyright (C) 2019 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

syntax = "proto2";
package android.stats.mediaprovider;
option java_multiple_files = true;

enum VolumeType {
    // Volume is unknown
    UNKNOWN = 0;
    // Volume is MediaStore.VOLUME_INTERNAL
    INTERNAL = 1;
    // Volume is MediaStore.VOLUME_EXTERNAL_PRIMARY
    EXTERNAL_PRIMARY = 2;
    // Volume is non-primary external storage
    EXTERNAL_OTHER = 3;
}

enum Uri {
    URI_UNSPECIFIED = 0;
    URI_MEDIA = 1;
    URI_MEDIA_PICKER = 2;
    URI_MEDIA_REDACTED = 3;
    URI_MEDIA_DOCUMENT = 4;
}

enum FuseOp {
    FUSE_OP_UNSPECIFIED = 0;
    UNLINK = 1;
    OPENDIR = 2;
    ACCESS = 3;
    RENAME = 4;
    OPEN = 5;
    READ = 6;
    READDIR = 7;
    CREATE = 8;
    GETATTR = 9;
    SETATTR = 10;
    MKDIR = 11;
    RMDIR = 12;
    LOOKUP = 13;
    LOOKUP_POSTFILTER = 14;
    INIT = 15;
    DESTROY = 16;
    FORGET = 17;
    CANONICAL_PATH = 18;
    MKNOD =  19;
    FLUSH = 20;
    RELEASE = 21;
    FSYNC = 22;
    READDIR_POSTFILTER = 23;
    RELEASEDIR = 24;
    FSYNCDIR = 25;
    STATFS = 26;
    WRITE_BUF = 27;
    FALLOCATE = 28;
    FORGET_MULTI = 29;
}

enum MediaProviderOp {
    MEDIA_PROVIDER_OP_UNSPECIFIED = 0;
    ON_CREATE = 1;
    BULK_INSERT = 2;
    INSERT = 3;
    DELETE = 4;
    UPDATE = 5;
    OPEN_FILE = 6;
    OPEN_TYPED_ASSET_FILE = 7;
    OPEN_FILE_ASYNC = 8;
    OPEN_ASSET_FILE_ASYNC = 9;
    APPLY_BATCH = 10;
    ATTACH_VOLUME = 11;
    DETACH_VOLUME = 12;

    // MediaStore Call APIs
    RESOLVE_PLAYLIST_MEMBERS_CALL = 20;
    GET_VERSION_CALL = 21;
    GET_GENERATION_CALL = 22;
    GET_DOCUMENT_URI_CALL = 23;
    GET_MEDIA_URI_CALL = 24;
    GET_REDACTED_MEDIA_URI_CALL = 25;
    GET_REDACTED_MEDIA_URI_LIST_CALL = 26;
    CREATE_WRITE_REQUEST_CALL = 27;
    CREATE_FAVORITE_REQUEST_CALL = 28;
    CREATE_TRASH_REQUEST_CALL = 29;
    CREATE_DELETE_REQUEST_CALL = 30;
    MARK_MEDIA_AS_FAVORITE = 31;
    PICKER_TRANSCODE_CALL = 32;
    SYNC_PROVIDERS_CALL = 33;
    BULK_UPDATE_OEM_METADATA_CALL = 34;
}
