/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

syntax = "proto2";

package android.os.statsd.vcn;

import "frameworks/proto_logging/stats/atoms.proto";
import "frameworks/proto_logging/stats/atom_field_options.proto";
import "frameworks/proto_logging/stats/enums/stats/vcn/vcn.proto";

option java_package = "com.android.os.vcn";
option java_multiple_files = true;

extend Atom {
  optional VcnGatewayConnectionStateChanged
      vcn_gateway_connection_state_changed = 1176 [(module_name) = "vcn"];
  optional VcnNetworkStateChanged vcn_network_state_changed = 1177
      [(module_name) = "vcn"];
  optional VcnUnderlyingNetworksStateChanged
      vcn_underlying_networks_state_changed = 1178 [(module_name) = "vcn"];
  optional VcnUnderlyingNetworkSwitched vcn_underlying_network_switched = 1204
      [(module_name) = "vcn"];
  optional VcnNetworkValidationStatusReported
      vcn_network_validation_status_reported = 1234 [(module_name) = "vcn"];
  optional IpSecPacketLossDetectorReported ip_sec_packet_loss_detector_reported =
      1310 [(module_name) = "vcn"];
  optional VcnDataStallIkeUpdated
      vcn_data_stall_ike_updated = 1347 [(module_name) = "vcn"];
}

/**
 * Log for state changes of VcnGatewayConnection.
 *
 * Logged from:
 *   packages/modules/Connectivity/Vcn/service-b/src/com/android/server/vcn/VcnGatewayConnection.java
 * Estimated Logging Rate: <10 per device per day
 */
message VcnGatewayConnectionStateChanged {
    // Unique ID of the VcnGatewayConnection instance. This ID is derived from
    // the gateway configuration and represents a specific instance of a gateway
    // connection. A new ID will be generated if a gateway is torn down and
    // restarted for the same configuration.
    optional int32 gw_id = 1;
    // Represents the reason VcnGatewayConnection may be torn down.
    optional android.stats.vcn.VcnGatewayTeardownReason gw_teardown_reason = 2;
    // Whether it is in SAFE_MODE state.
    optional bool is_in_safe_mode = 3;
}

/**
 * Log for state changes of VCN network of a particular VcnGatewayConnection.
 *
 * Logged from:
 *   packages/modules/Connectivity/Vcn/service-b/src/com/android/server/vcn/VcnGatewayConnection.java
 * Estimated Logging Rate: <10 per device per day
 */
message VcnNetworkStateChanged {
    // gw_id associated with the relevant VcnGatewayConnection.
    optional int32 gw_id = 1;
    // Unique ID of the VCN network brought up.
    optional int32 network_id = 2;
    // Whether the network is connected or has disconnected.
    optional bool is_connected = 3;
    // Whether the network has NetworkAgent.VALIDATION_STATUS_VALID.
    optional bool is_validated = 4 [deprecated = true];
}

/**
 * Log results of validation attempts on VCN network of a particular VcnGatewayConnection.
 *
 * Logged from:
 *   packages/modules/Connectivity/Vcn/service-b/src/com/android/server/vcn/VcnGatewayConnection.java
 * Estimated Logging Rate: <1k per device per day
 */
message VcnNetworkValidationStatusReported {
    // gw_id associated with the relevant VcnGatewayConnection.
    optional int32 gw_id = 1;
    // Unique ID of the VCN network brought up.
    optional int32 network_id = 2;

    optional android.stats.vcn.ValidationStatus prev_validation_status = 3;
    optional android.stats.vcn.ValidationStatus new_validation_status = 4;
}

/**
 * Log for state changes of underlying networks tracked by a particular VcnGatewayConnection.
 *
 * Logged from:
 *   packages/modules/Connectivity/Vcn/service-b/src/com/android/server/vcn/routeselection/UnderlyingNetworkController.java
 * Estimated Logging Rate: <10 per device per day
 */
message VcnUnderlyingNetworksStateChanged {
    // gw_id associated with the relevant VcnGatewayConnection.
    optional int32 gw_id = 1;
    // The number of validated underlying networks tracked by the VcnGatewayConnection's UnderlyingNetworkController.
    optional int32 validated_underlying_network_count = 2;
}

/**
 * Log for selected underlying network changed on a particular VcnGatewayConnection.
 *
 * Logged from:
 *   packages/modules/Connectivity/Vcn/service-b/src/com/android/server/vcn/VcnGatewayConnection.java
 * Estimated Logging Rate: <10 per device per day
 */
message VcnUnderlyingNetworkSwitched {
  // gw_id associated with the relevant VcnGatewayConnection.
  optional int32 gw_id = 1;

  // Transports of the network we switched from.
  optional android.stats.vcn.TransportMask old_network = 2;
  // Transports of the network we switched to.
  optional android.stats.vcn.TransportMask new_network = 3;
  // Handoff latency in milliseconds.
  optional int32 handoff_latency_ms = 4 [(unit) = UNIT_MILLISECONDS];
}

/**
 * Log for Ike mobility updates triggered by data stall recovery on a particular VcnGatewayConnection.
 *
 * Logged from:
 *   packages/modules/Connectivity/Vcn/service-b/src/com/android/server/vcn/VcnGatewayConnection.java
 * Estimated Logging Rate: <10 per device per day
 */
message VcnDataStallIkeUpdated {
  // gw_id associated with the relevant VcnGatewayConnection.
  optional int32 gw_id = 1;
  // Transports of the underlying network reported for data stall.
  optional android.stats.vcn.TransportMask underlying_network = 2;
  // Handoff latency in milliseconds.
  optional int32 handoff_latency_ms = 3 [(unit) = UNIT_MILLISECONDS];
}

/**
 * Log results of IPSec Packet Loss detector.
 *
 * Logged from:
 *   packages/modules/Connectivity/Vcn/service-b/src/com/android/server/vcn/routeselection/IpSecPacketLossDetector.java
 * Estimated Logging Rate:
 *   Peak: 1 time per 10s. Avg: ~300 times per device per day (1 VCN session of ~45min per device per day)
 */
message IpSecPacketLossDetectorReported {
  // gw_id associated with the relevant VcnGatewayConnection.
  optional int32 gw_id = 1;
  // Transports of the network evaluated, mostly whether CELLULAR or WIFI.
  optional android.stats.vcn.TransportMask transport_mask = 2;
  optional int32 signal_strength = 3; // For TRANSPORT_MASK_WIFI, RSSI.
  optional int32 packet_loss_percent = 4 [(unit) = UNIT_PERCENTAGE];
  optional android.stats.vcn.IpSecPacketLossResultType result_type = 5;
  // Configured packet loss % threshold at which detector will consider as lossy.
  optional int32 configured_packet_loss_threshold = 6 [(unit) = UNIT_PERCENTAGE];
}