/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

syntax = "proto2";

package android.os.statsd.wearsysui;

import "frameworks/proto_logging/stats/atoms.proto";
import "frameworks/proto_logging/stats/atom_field_options.proto";
import "frameworks/proto_logging/stats/enums/app/wearsysui/wearsysui_enums.proto";

option java_package = "com.android.os.wearsysui";
option java_multiple_files = true;

extend Atom {
  // Pushed Atom
  optional WearPowerMenuOpened wear_power_menu_opened = 731
  [(module) = "framework"];
  optional WearAssistantOpened wear_assistant_opened = 755
  [(module) = "framework"];
  optional FirstOverlayStateChanged first_overlay_state_changed = 917
  [(module) = "framework"];
  optional WearTilePeekDurationReported wear_tile_peek_duration_reported = 1199
      [(module) = "wearsysui"];
  optional WearTileTapReported wear_tile_tap_reported = 1200 [(module) = "wearsysui"];
  optional WearWatchFaceContentOverlayEventReported wear_watch_face_content_overlay_event_reported = 1212
      [(module) = "wearsysui"];
}

/**
 * Logs whenever the Power Menu is opened for Wear
 * Logged from :
 * vendor/google_clockwork/packages/SystemUI/src/com/google/android/clockwork/systemui/statusbar/WearGlobalActionsProvider.java
 */
message WearPowerMenuOpened {
  optional bool device_provisioned = 1;
  optional bool setup_wizard_completed = 2;
}

/**
 * Logs whenever Assistant is opened for Wear
 * Logged from :
 * vendor/google_clockwork/packages/SystemUI/src/com/google/android/clockwork/systemui/assist/WearAssistManager.java
 */
message WearAssistantOpened {
  optional bool in_retail_mode = 1;
}

/**
 * Logs for First Overlay State Changes
 *
 */
message FirstOverlayStateChanged {
    enum OverlayState {
        UNKNOWN = 0;
        // The overlay is shown during boot.
        SHOWN = 1;
        // The overlay is dismissed to indicate boot is complete.
        DISMISSED = 2;
    }

    optional OverlayState overlay_state = 1;
    // The time when first overlay state change has occurred, in milliseconds since the system was booted.
    optional int64 state_change_time_ms = 2;
    // Indicates whether the lock screen is enabled
    optional bool is_locked_screen_active = 3;
}

/**
 * Logs for Tile Peek Duration.
 * Logged from:
 * java/com/google/android/wearable/sysui/mainui/carousel/logging/SysUiTilesSessionLogger.java
 * Logged when:
 * 1. Tile becomes visible.
 * 2. Tile peek is cancelled - by either a swipe, tap, swipe to dismiss or a button press.
 */
message WearTilePeekDurationReported {
  enum TilePeekState {
    UNKNOWN = 0;
    START = 1;
    END = 2;
  }

  // Component uid of the tile provider
  optional int32 component_package_uid = 1 [(is_uid) = true];

  // Component class name of the tile provider, represents an activity name.
  optional string component_class_name = 2;

  // Duration the tile was visible for in milliseconds
  optional int32 tile_peek_duration_ms = 3;

  // Position of the tile in the tile tray
  optional int32 tile_position = 4;

  // Type of event for the tile peek - start or end
  optional TilePeekState tile_peek_state = 5;
}

/**
 * Logs for Tile Tap.
 * Logged from:
 * java/com/google/android/wearable/sysui/mainui/carousel/logging/SysUiTilesSessionLogger.java
 * Logged when:
 * 1. Tile is tapped.
 */
message WearTileTapReported {
  // Component uid of the tile provider
  optional int32 component_package_uid = 1 [(is_uid) = true];

  // Component class name of the tile provider, represents an activity name.
  optional string component_class_name = 2;

  // Position of the tile in the tile tray
  optional int32 tile_position = 3;
}

// Atom logged when an event is reported for WF Content Overlay (WFCO) UI.
//
// Logged from: java/com/google/android/wearable/sysui/mainui/module/watchfaceoverlay/logging/WatchFaceOverlayStatsLogger.kt
//
// Logged when:
// 1. New content item is displayed on WFCO.
// 2. User interacts with the content item on WFCO.
message WearWatchFaceContentOverlayEventReported {
  // UiEvent ID associated with this event like UI_UPDATED, TAPPED, DISMISSED, OHG_INTERACTED, LONG_PRESS etc.
  optional int64 ui_event_id = 1;

  // The UID (to get pkg info) of the content provider.
  optional int32 uid = 2 [(is_uid) = true];

  // The type of content being displayed.
  optional android.app.wearsysui.WatchFaceContentOverlayEntryType entry_type = 3;

  // The type of the text being displayed.
  optional android.app.wearsysui.WatchFaceContentOverlayTextType text_type = 4;
}
