/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

syntax = "proto2";

package android.os.statsd.wearsysui;

import "frameworks/proto_logging/stats/atoms.proto";
import "frameworks/proto_logging/stats/atom_field_options.proto";
import "frameworks/proto_logging/stats/enums/app/wearsysui/wearsysui_enums.proto";
import "frameworks/proto_logging/stats/enums/app/wearservices/wearservices_enums.proto";

option java_package = "com.android.os.wearsysui";
option java_multiple_files = true;

extend Atom {
  // Pushed Atom
  optional WearPowerMenuOpened wear_power_menu_opened = 731
      [(module_name) = "framework"];
  optional WearAssistantOpened wear_assistant_opened = 755
      [(module_name) = "framework"];
  optional FirstOverlayStateChanged first_overlay_state_changed = 917
      [(module_name) = "framework"];
  optional WearTilePeekDurationReported wear_tile_peek_duration_reported = 1199
      [(module_name) = "wearsysui"];
  optional WearTileTapReported wear_tile_tap_reported = 1200
      [(module_name) = "wearsysui"];
  optional WearLiveEntryEventReported wear_live_entry_event_reported = 1212
      [(module_name) = "wearsysui"];
  optional WearLiveUpdateSettingEventReported
      wear_live_update_setting_event_reported = 1226
      [(module_name) = "wearsysui"];
  optional WearTrayAnimationStarted wear_tray_animation_started = 1229
      [(module_name) = "wearsysui"];
  optional WearTrayAnimationFinished wear_tray_animation_finished = 1230
      [(module_name) = "wearsysui"];
  optional WearSysUiCarouselAddTileButtonInteractionReported
      wear_sys_ui_carousel_add_tile_button_interaction_reported = 1238
      [(module_name) = "wearsysui"];
  optional WearSysUiCarouselTileManagementEditButtonTapped
      wear_sys_ui_carousel_tile_management_edit_button_tapped = 1239
      [(module_name) = "wearsysui"];
  optional WearTrayOpenKeyEventOccurred wear_tray_open_key_event_occurred = 1257
      [(module_name) = "wearsysui"];
  optional WearNotificationUiEventReported wear_notification_ui_event_reported =
      1258 [(module_name) = "wearsysui"];
  optional WearNotificationTrayEventReported
      wear_notification_tray_event_reported = 1259
      [(module_name) = "wearsysui"];
  optional WearSystemTrayIconUpdated wear_system_tray_icon_updated = 1264
      [(module_name) = "wearsysui"];
  optional WearNotificationProcessingSkipped wear_notification_processing_skipped = 1309
      [(module_name) = "wearsysui"];
}

/**
 * Logs whenever the Power Menu is opened for Wear
 * Logged from :
 * vendor/google_clockwork/packages/SystemUI/src/com/google/android/clockwork/systemui/statusbar/WearGlobalActionsProvider.java
 */
message WearPowerMenuOpened {
  optional bool device_provisioned = 1;
  optional bool setup_wizard_completed = 2;
}

/**
 * Logs whenever Assistant is opened for Wear
 * Logged from :
 * vendor/google_clockwork/packages/SystemUI/src/com/google/android/clockwork/systemui/assist/WearAssistManager.java
 */
message WearAssistantOpened {
  optional bool in_retail_mode = 1;
}

/**
 * Logs for First Overlay State Changes
 *
 */
message FirstOverlayStateChanged {
    enum OverlayState {
        UNKNOWN = 0;
        // The overlay is shown during boot.
        SHOWN = 1;
        // The overlay is dismissed to indicate boot is complete.
        DISMISSED = 2;
    }

    optional OverlayState overlay_state = 1;
    // The time when first overlay state change has occurred, in milliseconds since the system was booted.
    optional int64 state_change_time_ms = 2;
    // Indicates whether the lock screen is enabled
    optional bool is_locked_screen_active = 3;
}

/**
 * Logs for Tile Peek Duration.
 * Logged from:
 * java/com/google/android/wearable/sysui/mainui/carousel/logging/SysUiTilesSessionLogger.java
 * Logged when:
 * 1. Tile becomes visible.
 * 2. Tile peek is cancelled - by either a swipe, tap, swipe to dismiss or a button press.
 */
message WearTilePeekDurationReported {
  enum TilePeekState {
    UNKNOWN = 0;
    START = 1;
    END = 2;
  }

  // Component uid of the tile provider
  optional int32 component_package_uid = 1 [(is_uid) = true];

  // Component class name of the tile provider, represents an activity name.
  optional string component_class_name = 2;

  // Duration the tile was visible for in milliseconds
  optional int32 tile_peek_duration_ms = 3;

  // Position of the tile in the tile tray
  optional int32 tile_position = 4;

  // Type of event for the tile peek - start or end
  optional TilePeekState tile_peek_state = 5;

  // The container type for the tile or widget. For tile, this will be
  // fullscreen always. For widgets, this value is specified when the widget
  // has been added. Value -1 is used to indicate that this field is not used.
  optional int32 container_type = 6;

  // Unique id of the instance of a tile or widget
  optional int32 instance_id = 7;
}

/**
 * Logs for Tile Tap.
 * Logged from:
 * java/com/google/android/wearable/sysui/mainui/carousel/logging/SysUiTilesSessionLogger.java
 * Logged when:
 * 1. Tile is tapped.
 */
message WearTileTapReported {
  // Component uid of the tile provider
  optional int32 component_package_uid = 1 [(is_uid) = true];

  // Component class name of the tile provider, represents an activity name.
  optional string component_class_name = 2;

  // Position of the tile in the tile tray
  optional int32 tile_position = 3;

  // The container type for the tile or widget. For tile, this will be
  // fullscreen always. For widgets, this value is specified when the widget
  // has been added. Value -1 is used to indicate that this field is not used.
  optional int32 container_type = 4;

  // Unique id of the instance of a tile or widget
  optional int32 instance_id = 5;
}

// Atom logged when an event is reported for Live Entry UI.
//
// Logged from: java/com/google/android/wearable/sysui/mainui/module/contentmanager/liveentry/LiveEntryStatsLogger.java
//
// Logged when:
// 1. New content item is displayed on live entry UI from WF Overlay or Notifications.
// 2. User interacts with live entry item.
message WearLiveEntryEventReported {
  // UiEvent ID associated with this event like UI_UPDATED, TAPPED, DISMISSED, OHG_INTERACTED, LONG_PRESS etc.
  optional int32 event_id = 1;

  // The package name of the app that is providing the content. Note this includes
  // packages not installed on the watch, so it cannot be UID.
  optional string package_name = 2;

  // The type of content being displayed.
  optional android.app.wearsysui.LiveEntryContentType content_type = 3;

  // The type of the text being displayed.
  optional android.app.wearsysui.LiveEntryTextType text_type = 4;
}
/**
 * Atom logged when an event is reported for Live Update Setting UI.
 *
 * Logged from :
 * java/com/google/android/wearable/sysui/mainui/module/watchfaceoverlay/penguin/settings/logging/LiveUpdateSettingStatsLogger.kt
 * Logged when:
 * 1. Live Update Setting is shown to the user.
 * 2. User interacts with the Live Update Setting.
 */
message WearLiveUpdateSettingEventReported{
  // UiEvent for the interaction that happened ex. LIVE_UPDATE_SETTING_SHOWN, SELECTED etc.
  optional int32 event_id = 1;

  // Package name of the app for which settings is shown. Note this includes
  // packages not installed on the watch, so it cannot be UID.
  optional string package_name = 2;

  // Source from which Quick Setting was entered
  optional android.app.wearsysui.LiveUpdateSettingEntrySource entry_source = 3;

   // Setting option selected by the user for this content provider
  optional android.app.wearsysui.LiveUpdateSettingOption option_type = 4;
}

// Atom logged when a tray animation is started.
//
// Logged from: java/com/google/android/clockwork/sysui/common/syshealthlogging/ObserveTrayOpenStateForLatencyRecording.kt
//
// Logged ~6 times per day per device.
message WearTrayAnimationStarted {
}

// Atom logged when a tray animation is finished.
//
// Logged from: java/com/google/android/clockwork/sysui/common/syshealthlogging/ObserveTrayOpenStateForLatencyRecording.kt
//
// Logged ~6 times per day per device.
message WearTrayAnimationFinished {
}

/**
 * Logged when the user interacts with the "add tile" button.
 *
 * Logged from:
 *   java/com/google/android/clockwork/sysui/mainui/module/carousel/ui/compose/addtile/AddTileViewModel.kt
 *   java/com/google/android/clockwork/sysui/mainui/module/carousel/management/LlmWidgetsButtonBinder.kt
 */
message WearSysUiCarouselAddTileButtonInteractionReported {
  // The index of the add tile button in the carousel.
  optional int32 carousel_index = 1;
  // The total number of items in the carousel.
  optional int32 total_carousel_size = 2;

  enum EventType {
    UNKNOWN_EVENT_TYPE = 0;
    // The add tile button was viewed.
    VIEWED = 1;
    // The add tile button was tapped.
    TAPPED = 2;
  }
  // The type of interaction event.
  optional EventType event_type = 3;

  enum Source {
    UNKNOWN_SOURCE = 0;
    // The interaction was from the carousel.
    CAROUSEL = 1;
    // The interaction was from tile management.
    TILE_MANAGEMENT = 2;
  }
  // The source of the interaction.
  optional Source source = 4;
}

/**
 * Logged when user taps on tile edit (pencil) button in tile management.
 *
 * Logged from:
 *   java/com/google/android/clockwork/sysui/mainui/module/carousel/management/TileManagerController.kt
 */
message WearSysUiCarouselTileManagementEditButtonTapped {
  // Unique id of the instance of a tile or widget being edited.
  optional int32 instance_id = 1;
  // Component uid of the tile provider being edited.
  optional int32 component_package_uid = 2 [(is_uid) = true];
  // Component class name of the tile provider being edited, represents an activity name.
  optional string component_class_name = 3;
  // The index of the tile in the wear services tile list.
  optional int32 tile_wear_services_index = 4;
}

// Atom logged when a tray open key event is received by sysui.
//
// This is sent when the watch is offloaded and the user rotates the crown or swipes up/down on the screen.
//
// Logged from  https://source.corp.google.com/piper///depot/google3/java/com/google/android/clockwork/sysui/common/uimodetray/TrayEventsHandler.java
// Logged ~6 times per day per device.
message WearTrayOpenKeyEventOccurred {
  // The key code for the key event that triggered the tray open.
  optional int32 key_code = 1;
  // The timestamp from the key event.
  // https://developer.android.com/reference/android/view/KeyEvent#getEventTime()
  optional int64 event_time_ms = 2;
}

/**
 * Atom containing user interaction associated with a notification.
 *
 * Logged from: google3/java/com/google/android/clockwork/sysui/common/logging/NotificationLogger.java
 *
 */
message WearNotificationUiEventReported {
  // UiEvent of the event reported including UI shown, UI removed, touch, scrolled, RSB scrolled, open on phone, open on watch etc.
  optional int32 event_id = 1;
  // The package name of the app that is providing the content. Note this includes
  // packages not installed on the watch, so it cannot be UID.
  optional string package_name = 2;
  // Surface where full view is being shown
  optional android.app.wearsysui.NotificationSurface surface = 3;
  // State of the notification
  optional android.app.wearsysui.NotificationState state = 4;
  // Instance of the notification or a given surface. This is needed since we
  // can have 1+ instances of HUN on top of each other from same app.
  optional int32 instance = 5;
}

/**
 * Atom logged when an event happens in the notification tray.
 *
 * Logged from: google3/java/com/google/android/clockwork/sysui/common/logging/NotificationLogger.java
 *
 */
message WearNotificationTrayEventReported {
  // UiEvent of the event reported (this includes TRAY_OPENED)
  optional int32 event_id = 1;
  // Number of live entries present in the tray
  optional int32 num_liveentries = 2;
  // The live entries in the tray, in the order that they appear there
  optional WearLiveEntriesList live_entries_list = 3 [(log_mode) = MODE_BYTES];
  // Number of notifications present in the tray
  optional int32 num_notifications = 4;
  // The notifications in the panel, in the order that they appear there
  optional WearNotificationsList notifications_list = 5 [(log_mode) = MODE_BYTES];
}

/**
 * Proto describing the live entries present.
 */
message WearLiveEntries {
  // Package identifier. An integer index assigned to each distinct package generated on the device to distinguish apps on a single device.
  // Not the app uid and cannot be translated to package name.
  optional int32 package_id = 1;
  // Live Entry content type
  optional android.app.wearsysui.LiveEntryContentType content_type = 2;
  // Live Entry text type
  optional android.app.wearsysui.LiveEntryTextType text_type = 3;
}

/**
 * Proto describing the list of live entries present.
 */
message WearLiveEntriesList {
  repeated WearLiveEntries live_entries = 1;
}

/**
 * Proto describing metadata about the content.
 */
message WearNotification {
  // Package identifier. An integer index assigned to each distinct package generated on the device to distinguish apps on a single device.
  // Not the app uid and cannot be translated to package name.
  optional int32 package_id = 1;
  // The style of the notification
  optional android.app.wearservices.NotificationStyle style = 2;
  // The category of the notification
  optional android.app.wearservices.NotificationCategory category = 3;
}

/**
 * Proto describing the list of notifications present.
 */
message WearNotificationsList {
  repeated WearNotification notifications = 1;
}

/**
 * Atom logged when a system tray icon is updated.
 *
 * Logged from: google3/java/com/google/android/clockwork/sysui/common/logging/WatchFaceOverlayLogger.kt
 *
 * Estimated Logging Rate:
 * Peak: 40 times per day per device | Avg: 6 per device per day
 *
 */
message WearSystemTrayIconUpdated {
  // Type of icon shown on the screen
  optional android.app.wearsysui.IconType icon_type = 1;
  // The new state of the icon.
  optional android.app.wearsysui.State state = 2;
}

/**
 * Atom logged when a notification processing is skipped.
 *
 * Logged from: google3/java/com/google/android/clockwork/sysui/common/logging/NotificationLogger.java
 *
 */
message WearNotificationProcessingSkipped {
  // The reason why the notification processing was skipped.
  optional android.app.wearsysui.SkippedReason reason = 1;
}
