/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
syntax = "proto2";
package android.stats.vcn;

enum VcnGatewayTeardownReason {
    GATEWAY_TEARDOWN_REASON_UNSPECIFIED = 0;
    GATEWAY_TEARDOWN_REASON_NONE = 1; // Gateway is connected
    GATEWAY_TEARDOWN_REASON_INTERNAL_ERROR = 2;
    GATEWAY_TEARDOWN_REASON_NETWORK_AGENT_UNWANTED = 3;
    GATEWAY_TEARDOWN_REASON_REQUESTED = 4;
  }

// Represents the transport types of a network as a bitmask.
// This design allows for supporting multi-transport types network by combining
// values using bitwise OR operations.
//
// For TRANSPORT_MASK_NONE tag number, it's chosen to be less than max allowed
// enum tag number (2**29 -1). So this should support up to MAX_TRANSPORT=27.
enum TransportMask {
    TRANSPORT_MASK_UNSPECIFIED = 0;
    TRANSPORT_MASK_NONE = 268435456; // No Network. 1 << 28
    TRANSPORT_MASK_CELLULAR = 1; // 1 << TRANSPORT_CELLULAR(=0)
    TRANSPORT_MASK_WIFI = 2; // 1 << TRANSPORT_WIFI(=1)

    // Additional transport types examples:
    // TRANSPORT_MASK_WIFI_VPN = 18; // 1 << TRANSPORT_WIFI | 1 << TRANSPORT_VPN
}

// Represents the validation status of a network.
enum ValidationStatus {
    VALIDATION_STATUS_UNSPECIFIED = 0;
    // There hasn't been any completed validation attempt yet.
    VALIDATION_STATUS_PENDING = 1;
    VALIDATION_STATUS_VALID = 2;
    VALIDATION_STATUS_NOT_VALID = 3;
}

// Represents the result of the IPsec packet loss detection.
// For each type's details, see packages/modules/Connectivity/Vcn/service-b/src/com/android/server/vcn/routeselection/IpSecPacketLossDetector.java
enum IpSecPacketLossResultType {
    IPSEC_PACKET_LOSS_RESULT_TYPE_UNSPECIFIED = 0;
    IPSEC_PACKET_LOSS_RESULT_TYPE_VALID = 1;
    IPSEC_PACKET_LOSS_RESULT_TYPE_SEQ_DIFF_TOO_SMALL = 2;
    IPSEC_PACKET_LOSS_RESULT_TYPE_UNUSUAL_SEQ_NUM_LEAP = 3;
    IPSEC_PACKET_LOSS_RESULT_TYPE_UNEXPECTED_ERROR = 4;
    IPSEC_PACKET_LOSS_RESULT_TYPE_PACKETS_TOO_OLD = 5;
}