/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

syntax = "proto2";

package android.os.statsd.wear.physicalux;

import "frameworks/proto_logging/stats/atoms.proto";
import "frameworks/proto_logging/stats/atom_field_options.proto";
import "frameworks/proto_logging/stats/enums/view/enums.proto";
import "frameworks/proto_logging/stats/enums/wear/physicalux/enums.proto";

option java_package = "com.android.os.wear.physicalux";
option java_multiple_files = true;

extend Atom {
  optional WearGestureSubscriptionChanged wear_gesture_subscription_changed =
      1095 [(module_name) = "framework"];
  optional WearGestureReported wear_gesture_reported = 1096
      [(module_name) = "framework"];
  optional WearGestureDetectionStateChanged
      wear_gesture_detection_state_changed = 1097 [(module_name) = "framework"];
  optional WearHardwareButtonInteractionReported
      wear_hardware_button_interaction_reported = 1244
      [(module_name) = "framework"];
  optional WearGestureExperienceEventReported
      wear_gesture_experience_event_reported = 1304
      [(module_name) = "framework"];
}

// This file contains atom related to Gestures in Wear.

/**
 * Logged when a client's subscription to gestures changes.
 *
 * Logged from:
 * package: frameworks/opt/wear/src/com/android/clockwork/gesture
 */
message WearGestureSubscriptionChanged {
    // The UID that subscribed to gesture events.
    optional int32 uid = 1 [(is_uid) = true];
    // The actions that are subscribed for.
    // This will be empty when the client unsubscribes.
    repeated com.google.android.clockwork.physicalux.GestureAction actions = 2;
}

/**
 * Logged when a gesture event is reported.
 *
 * Logged from:
 * package: frameworks/opt/wear/src/com/android/clockwork/gesture
 */
message WearGestureReported {
    // The gesture action of the event for local device use cases.
    // Note that this is the action reported for the foreground subscribers.
    optional com.google.android.clockwork.physicalux.GestureAction action = 1;
    // The raw gesture of the event.
    optional com.google.android.clockwork.physicalux.Gesture gesture = 2;
    // The UIDs to whom this event was reported.
    // Note that this is the UIDs of the foreground subscribers. The UIDs for the background
    // subscribers is included in the respective _background_uids fields.
    repeated int32 uids = 3 [(is_uid) = true];
    // The system action that was triggered by the gesture.
    optional com.google.android.clockwork.physicalux.SystemAction system_action = 4;
    // The display state when the gesture event happened.
    optional android.view.DisplayStateEnum display_state = 5;
    // The gesture action of the event for remote device use cases.
    // Note that this is the action reported for the foreground subscribers.
    optional com.google.android.clockwork.physicalux.GestureAction remote_action = 6;
    // The UIDs of local background subscribers who received the event.
    repeated int32 local_background_uids = 7 [(is_uid) = true];
    // The UIDs of remote background subscribers who received the event.
    repeated int32 remote_background_uids = 8 [(is_uid) = true];
}

/**
 * Logged when there is an event related to a gesture experience.
 *
 * Logged from:
 * package: frameworks/opt/wear/src/com/android/clockwork/gesture
 */
message WearGestureExperienceEventReported {
    // The UID that owns the gesture experience.
    optional int32 uid = 1 [(is_uid) = true];
    // The ID of the gesture experience.
    // A string that has no meaning in and of itself, and serves only as a unique identifier of a
    // certain gesture experience.
    optional string experience_id = 2;
    // The gesture experience event that happened.
    optional com.google.android.clockwork.physicalux.GestureExperienceEvent event = 3;
    // The gesture action associated with the event.
    optional com.google.android.clockwork.physicalux.GestureAction action = 4;
}

/**
 * Logged when the state of gesture detection changes.
 *
 * Logged from:
 * package: frameworks/opt/wear/src/com/android/clockwork/gesture
 */
message WearGestureDetectionStateChanged {
    // The new gesture detection state
    optional com.google.android.clockwork.physicalux.GestureDetectionState state = 1;
    // The gesture actions with active subscriptions
    repeated com.google.android.clockwork.physicalux.GestureAction subscribed_actions = 2;
}

/**
 * Logged when a hardware button is interacted with.
 *
 * Logged from:
 * package: frameworks/opt/wear/src/com/android/clockwork/input/...
 */
message WearHardwareButtonInteractionReported {
    // The hardware button that was interacted with.
    optional HardwareButtonType hardware_button_type = 1;
    // The interaction type of the hardware button.
    optional HardwareButtonInteractionType hardware_button_interaction_type = 2;

    enum HardwareButtonType {
        HARDWARE_BUTTON_UNSPECIFIED = 0;
        // The crown button on the watch.
        HARDWARE_BUTTON_CROWN = 1;
        // The stem primary hardware button on the watch.
        HARDWARE_BUTTON_STEM_PRIMARY = 2;
    }

    enum HardwareButtonInteractionType {
        HARDWARE_BUTTON_INTERACTION_UNSPECIFIED = 0;
        // The hardware button was pressed.
        HARDWARE_BUTTON_INTERACTION_PRESSED = 1;
        // The hardware button was double-pressed.
        HARDWARE_BUTTON_INTERACTION_DOUBLE_PRESSED = 2;
        // The hardware button was long-pressed.
        HARDWARE_BUTTON_INTERACTION_LONG_PRESSED = 3;
        // The hardware button was very long-pressed.
        HARDWARE_BUTTON_VERY_LONG_PRESSED = 4;
    }
}
