/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

syntax = "proto2";

package android.os.statsd.microxr;

import "frameworks/proto_logging/stats/atoms.proto";
import "frameworks/proto_logging/stats/atom_field_options.proto";

option java_package = "com.android.os.statsd.microxr";
option java_multiple_files = true;

extend Atom {
  // Pushed atoms.
  optional MicroXrDeviceBootCompleteReported
      micro_xr_device_boot_complete_reported = 901 [(module) = "microxr"];
  optional MicroXrDonDoffStateChanged micro_xr_don_doff_state_changed = 1182
      [(module) = "microxr"];
  optional MicroXrSoundTriggerDetected micro_xr_sound_trigger_detected = 1188
      [(module) = "microxr"];
  optional MicroXrAudioPlaybackCompleted micro_xr_audio_playback_completed = 1189
      [(module) = "microxr"];
  optional MicroXrMcuCrashOccurred micro_xr_mcu_crash_occurred = 300000
      [(module) = "microxr-vendor"];
}

/**
 * Logged when a MicroXR Device is done booting.
 */
message MicroXrDeviceBootCompleteReported {
  // Device ready elapsed time in milliseconds.
  // Logged from microxr-system-ui.
  optional int64 device_ready_time_millis = 1;
}

/**
 * Represents the current Don or Doff state.
 */
enum DonDoffState {
  DON_DOFF_STATE_UNKNOWN = 0;
  // Glasses are "donned", i.e. worn.
  DON_DOFF_STATE_DONNED = 1;
  // Glasses are "doffed", i.e. not worn.
  DON_DOFF_STATE_DOFFED = 2;
  // Don/doff detection is disabled.
  DON_DOFF_STATE_DISABLED = 3;
}

/**
 * Logged each time the don/doff state changed
 *
 * Estimated Logging Rate:
 *   Average on the order of tens per day at most
 */
message MicroXrDonDoffStateChanged {
  optional DonDoffState don_doff_new_state = 1;
}

/**
 * Logged when the MCU crashes.
 */
message MicroXrMcuCrashOccurred {
  // Atoms logged from Vendor require a reverse domain name field.
  // The expected value is "";
  optional string reverse_domain_name = 1;
}

/**
 * Logged when a sound trigger (hotword) is detected by a local 1st
 * stage activation.
 *
 * Estimated Logging Rate:
 *   Average on the order of tens or hundreds per day at most
 */
message MicroXrSoundTriggerDetected {
  enum ValidationType {
    VALIDATION_TYPE_UNSPECIFIED = 0;
    VALIDATION_TYPE_LOCAL = 1;
    VALIDATION_TYPE_REMOTE = 2;
  }

  enum ValidationStatus {
    VALIDATION_STATUS_UNSPECIFIED = 0;
    VALIDATION_STATUS_ACCEPTED = 1;
    VALIDATION_STATUS_REJECTED = 2;
  }

  optional ValidationType validation_type = 1;
  optional ValidationStatus validation_status = 2;
}

/**
 * Transport used by a media stream.
 */
enum MediaTransport {
  MEDIA_TRANSPORT_UNKNOWN = 0;

  // Transports that terminate on the AP (application processor).
  MEDIA_TRANSPORT_A2DP = 1;
  MEDIA_TRANSPORT_RFCOMM = 2;
  MEDIA_TRANSPORT_L2CAP = 3;
  MEDIA_TRANSPORT_WIFI = 4;

  // Transports that terminate on the MCU.
  MEDIA_TRANSPORT_OFFLOADED_A2DP = 5;
  MEDIA_TRANSPORT_OFFLOADED_RFCOMM = 6;
  MEDIA_TRANSPORT_OFFLOADED_L2CAP = 7;
}

/**
 * Logged when an audio playback stream completes.
 *
 * Estimated Logging Rate:
 *   Average on the order of tens per day at most
 */
message MicroXrAudioPlaybackCompleted {
  // Transport used by this playback stream.
  optional MediaTransport transport = 1;

  // Duration of the stream, in milliseconds. This is the wallclock duration
  // from stream start until stream end.
  optional int32 duration_ms = 2;

  // Duration of audio actually played, not counting underflows or gaps.
  optional int32 duration_played_ms = 3;

  //
  // Underflows
  //
  // An underflow occurs when audio is written to the speakers more slowly than
  // it is consumed by the speakers. Underflows are usually caused by late
  // arrival of network packets due to abnormally high congestion or latency.
  // Late packets are dropped.
  //
  // One "underflow" is a sequence of dropped packets. Each underflow has two
  // properties: a duration (how many packets were dropped) and a lateness (how
  // late the first underflowed packet arrived relative to its deadline).
  //
  // Underflow statistics are pre-aggregated histograms, instead of a separte
  // atom per underflow event, because this will be logged from an MCU which
  // buffer large queues of atoms and in pathological cases there may be large
  // numbers of underflows.
  //

  // Number of underflows.
  optional int32 underflows_total_count = 4;

  // Total (cumulative) duration of all underflows.
  optional int64 underflows_total_duration_ms = 5;

  // Histogram of underflow durations. Underflows cannot be shorter than the
  // packet duration, which is expected to be about 20ms. Standard advice is to
  // use fewer than 20 bins. Empirically, we expect most underflows are less than
  // 1 second.
  repeated int32 underflows_duration_histogram_ms = 6 [(histogram_bin_option).explicit_bins = {
    bin: 25
    bin: 50
    bin: 100
    bin: 250
    bin: 500
    bin: 1000
  }];

  // Total (cumulative) lateness of all underflows.
  optional int64 underflows_total_lateness_ms = 7;

  // Histogram of underflow lateness.
  repeated int32 underflows_lateness_histogram_ms = 8 [(histogram_bin_option).explicit_bins = {
    bin: 25
    bin: 50
    bin: 100
    bin: 250
    bin: 500
    bin: 1000
  }];
}
