/*
 * Copyright (C) 2024 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

syntax = "proto2";

package android.os.statsd.corenetworking.platform;

option java_package = "com.android.os.corenetworking.platform";
option java_multiple_files = true;

import "frameworks/proto_logging/stats/atoms.proto";
import "frameworks/proto_logging/stats/atom_field_options.proto";
import "frameworks/proto_logging/stats/enums/corenetworking/platform/enums.proto";

extend Atom {
    // pushed atom
    optional VpnConnectionReported vpn_connection_reported = 851 [(module) = "framework"];
}


/**
 * Logs the VPN connection stats for analysis performance of VPN
 *
 * Logs from: services/core/java/com/android/server/connectivity/Vpn.java.
 *
 */
message VpnConnectionReported {
  // VPN connection types defined in
  // frameworks/base/core/java/android/net/VpnManager.java
  optional android.corenetworking.platform.VpnType vpn_type = 1;

  // The IP address type in the VPN connection(IPv4/IPv6/IPv4v6)
  optional android.corenetworking.platform.IpType conn_ip_protocol = 2;

  // The IP protocol of the VPN server(IPv4/IPv6/IPv4v6)
  optional android.corenetworking.platform.IpType server_ip_protocol = 3;

  optional android.corenetworking.platform.VpnProfileType vpn_profile_type = 4;

  // Bitmasked value for allowed algorithms
  optional int32 allowed_algorithms = 5;

  // The MTU configuration of the VPN network
  optional int32 mtu = 6;

  // The list of underlying network type during the VPN connection
  repeated int32 underlying_network_type = 7;

  // The VPN connection state (connected/disconnected)
  optional bool connected = 8;

  // The android user id (0, 10, etc.) for the VPN. Different users can configure separate VPN
  // connections.
  optional int32 user_id = 9;
}
