/*
 * Copyright (C) 2024 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

syntax = "proto2";

package android.os.statsd.uprobestats;

import "frameworks/proto_logging/stats/atoms.proto";
import "frameworks/proto_logging/stats/atom_field_options.proto";
import "frameworks/proto_logging/stats/enums/os/enums.proto";

option java_package = "com.android.uprobestats";
option java_multiple_files = true;

extend Atom {
  optional TestUprobeStatsAtomReported test_uprobestats_atom_reported = 915
      [(module_name) = "uprobestats"];
  optional SetComponentEnabledSettingReported
      set_component_enabled_setting_reported = 1018
      [(module_name) = "uprobestats"];
  optional BalProcessControllerAddBoundClientUidReported bal_process_controller_add_bound_client_uid_reported = 1019 [deprecated = true];
  optional BindServiceLockedWithBalFlagsReported
      bind_service_locked_with_bal_flags_reported = 1045
      [(module_name) = "uprobestats"];
  optional AndroidGraphicsBitmapAllocated android_graphics_bitmap_allocated =
      1039 [(module_name) = "uprobestats"];
  optional AndroidGraphicsBitmapAllocationSnapshot
      android_graphics_bitmap_allocation_snapshot = 1118
      [(module_name) = "uprobestats"];
  optional DisabledLauncherActivityUidsReported
      disabled_launcher_activity_uids_reported = 1185
      [(module_name) = "uprobestats"];
  optional BindServiceLockedWithBalFlagsUidsReported
      bind_service_locked_with_bal_flags_uids_reported = 1186
      [(module_name) = "uprobestats"];
  optional AndroidGraphicsBitmapScaled android_graphics_bitmap_scaled = 1190
      [(module_name) = "uprobestats"];
  optional AccessibilityRuntimePermissionGrantReported
      accessibility_runtime_permission_grant_reported = 1217
      [(module_name) = "uprobestats"];
  optional UprobeStatsInternalError uprobe_stats_internal_error = 1274
      [(module_name) = "uprobestats"];
  optional UprobeStatsInvocation uprobe_stats_invocation = 1275
      [(module_name) = "uprobestats"];
  optional UprobeStatsBpfAttached uprobe_stats_bpf_attached = 1276
      [(module_name) = "uprobestats"];
  optional UprobeStatsBpfMapPolled uprobe_stats_bpf_map_polled = 1277
      [(module_name) = "uprobestats"];
  optional SuspiciousWakelockBehaviorReported
      suspicious_wakelock_behavior_reported = 1340
      [(module_name) = "uprobestats"];
}

/* Test atom, specifically for UprobeStats tests, not logged anywhere */
message TestUprobeStatsAtomReported {
    optional int64 first_field = 1;
    optional int64 second_field = 2;
    optional int64 third_field = 3;
}

/**
  * Logged by uprobestats on sampled devices, when
  * components have been enabled/disabled.
  *
  * This event happens quite frequently (multiple times per second) on boot,
  * and rarely thereafter. Implementation filters out packages in the
  * android and com.android namespaces, and states lower than
  * COMPONENT_ENABLED_STATE_DISABLED, which suppresses
  * nearly all of those early boot events.
  *
  * Given the above, expected logging rate is on the order of tens
  * in a day.
  */
message SetComponentEnabledSettingReported {
    optional string package_name = 1;
    optional string class_name = 2;
    optional int32 new_state = 3;
    optional string calling_package_name = 4;
    optional bool is_launcher_activity = 5;
}

/**
  * DEPRECATED - this message was never usesd and is replaced by
  * BindServiceLockedWithBalFlagsReported.
  *
  * Logged by uprobestats on sampled devices, when
  * unprivileged apps bind to privileged apps that
  * are allowed to do BAL (e.g. apps managing companion devices).
  *
  * Expected logging rate is on the order of tens in a day.
  */
message BalProcessControllerAddBoundClientUidReported {
    optional int32 client_uid = 1 [(is_uid) = true];
    optional string client_package_name = 2;
    optional int32 bind_flags = 3;
}

/**
  * Flags that can be passed to Context.bindService.
  *
  * This should be kept in sync with the `BIND_` flags in
  * frameworks/base/core/java/android/content/Context.java.
  */
enum BindServiceFlags {
    UNSPECIFIED = 0;
    BIND_AUTO_CREATE = 0x0001;
    BIND_DEBUG_UNBIND = 0x0002;
    BIND_NOT_FOREGROUND = 0x0004;
    BIND_ABOVE_CLIENT = 0x0008;
    BIND_ALLOW_OOM_MANAGEMENT = 0x0010;
    BIND_WAIVE_PRIORITY = 0x0020;
    BIND_IMPORTANT = 0x0040;
    BIND_ADJUST_WITH_ACTIVITY = 0x0080;
    BIND_NOT_PERCEPTIBLE = 0x00000100;
    BIND_ALLOW_ACTIVITY_STARTS = 0X000000200;
    BIND_INCLUDE_CAPABILITIES = 0x000001000;
    BIND_SHARED_ISOLATED_PROCESS = 0x00002000;
    BIND_PACKAGE_ISOLATED_PROCESS = 0x4000; // 1 << 14
    BIND_NOT_APP_COMPONENT_USAGE = 0x00008000;
    BIND_ALMOST_PERCEPTIBLE = 0x000010000;
    BIND_BYPASS_POWER_NETWORK_RESTRICTIONS = 0x00020000;
    BIND_ALLOW_FOREGROUND_SERVICE_STARTS_FROM_BACKGROUND = 0x00040000;
    BIND_SCHEDULE_LIKE_TOP_APP = 0x00080000;
    BIND_ALLOW_BACKGROUND_ACTIVITY_STARTS = 0x00100000;
    BIND_RESTRICT_ASSOCIATIONS = 0x00200000;
    BIND_ALLOW_INSTANT = 0x00400000;
    BIND_IMPORTANT_BACKGROUND = 0x00800000;
    BIND_ALLOW_WHITELIST_MANAGEMENT = 0x01000000;
    BIND_FOREGROUND_SERVICE_WHILE_AWAKE = 0x02000000;
    BIND_FOREGROUND_SERVICE = 0x04000000;
    BIND_TREAT_LIKE_ACTIVITY = 0x08000000;
    // @deprecated Repurposed to {@link #BIND_TREAT_LIKE_VISIBLE_FOREGROUND_SERVICE}.
    // BIND_VISIBLE = 0x10000000;
    BIND_TREAT_LIKE_VISIBLE_FOREGROUND_SERVICE = 0x10000000;
    BIND_SHOWING_UI = 0x20000000;
    BIND_NOT_VISIBLE = 0x40000000;
    // java.lang.Long flags that are not supported by proto enum.
    // BIND_EXTERNAL_SERVICE = 0x80000000;
    // BIND_EXTERNAL_SERVICE_LONG = 0x4000000000000000; // 1L << 62
    // BIND_BYPASS_USER_NETWORK_RESTRICTIONS = 0x100000000; // 0x1_0000_0000L
    // BIND_MATCH_QUARANTINED_COMPONENTS = 0x200000000 // 0x2_0000_0000L
    // BIND_ALLOW_FREEZE = 0x400000000; // 0x4_0000_0000L
}

/**
  * Logged by uprobestats on sampled devices, when
  * unprivileged apps bind to privileged apps that
  * are allowed to do BAL (e.g. apps managing companion devices).
  *
  * Expected logging rate is on the order of tens in a day.
  */
message BindServiceLockedWithBalFlagsReported {
    // The package name of the intent passed to bindServiceLocked.
    optional string intent_package_name = 1;
    // The flags passed to the bindServiceLocked call.
    // Must be one or a combination of the types in BindServiceFlags enum above.
    optional int64 flags = 2;
    // The package name of the app that called bindServiceLocked.
    optional string calling_package_name = 3;
    // The action of the intent passed to bindServiceLocked.
    optional string intent_action = 4;
    // The package name of the component passed to bindServiceLocked.
    // This package may gain the BAL capabilities of the calling_package_name.
    optional string intent_component_name_package = 5;
    // The class name of the component passed to bindServiceLocked.
    optional string intent_component_name_class = 6;
}

/**
 * Records Bitmap allocation events.
 *
 * Logged via Hummingbird for probes at android.graphics.Bitmap constructor.
 *
 * Estimated Logging Rate:
 *   Peak: 100 times in a minute | Avg: O(hundreds) per device per day
 */
message AndroidGraphicsBitmapAllocated {
    optional int32 uid = 1 [(is_uid) = true];
    optional int32 width = 2;
    optional int32 height = 3;
}

/**
 * Records snapshot of Bitmap allocations resident in memory.
 *
 * Logged via Hummingbird for probes at android.graphics.Bitmap constructor.
 *
 * Estimated Logging Rate:
 *   Peak: 100 times in a second | Avg: O(hundreds) per device per day
 */
message AndroidGraphicsBitmapAllocationSnapshot {
    optional int32 uid = 1 [(is_uid) = true];
    optional int32 width = 2;
    optional int32 height = 3;

    enum PixelStorageType {
      PIXEL_STORAGE_TYPE_UNSPECIFIED = 0;
      PIXEL_STORAGE_TYPE_HEAP = 1;
      PIXEL_STORAGE_TYPE_ASHMEM = 2;
      PIXEL_STORAGE_TYPE_HARDWARE = 3;
      PIXEL_STORAGE_TYPE_WRAPPED_PIXEL_REF = 4;
    };

    optional PixelStorageType pixel_storage_type = 4;

    // Unique identifier for the snapshot, generated randomly on the device
    // every time a snapshot is taken. Bitmaps in the same snapshot will have
    // the same snapshot_id.
    optional int64 snapshot_id = 5;
    enum SnapshotType {
        SNAPSHOT_TYPE_UNSPECIFIED = 0;
        SNAPSHOT_TYPE_RANDOM_SAMPLE = 1;
        SNAPSHOT_TYPE_MAX_ALLOCATION_SIZE = 2;
    }
    optional SnapshotType snapshot_type = 6;

    optional string activity_name = 7;
}

/**
  * Logged by uprobestats when launcher activities are disabled.
  * Disabling the launcher activity is a common abuse technique to
  * hide the malicious app's icon from the launcher.
  *
  * Logging rate is on the order of tens in a day.
  */
message DisabledLauncherActivityUidsReported {
    optional int32 calling_uid = 1 [(is_uid) = true];
    optional int32 disabled_activity_uid = 2 [(is_uid) = true];
}

/**
  * Logged by uprobestats on when apps bind to other apps while
  * passing along their BAL privileges (using the BAL flags).
  * Only privileged apps are allowed to do BAL
  * (e.g. apps managing companion devices), and vulnerabilities in those
  * apps can lead to unwanted BAL by malicious apps. This metric is used
  * to detect such vulnerabilities.
  *
  * Expected logging rate is on the order of tens in a day.
  */
message BindServiceLockedWithBalFlagsUidsReported {
    optional int32 binder_uid = 1 [(is_uid) = true];
    optional int32 bindee_uid = 2 [(is_uid) = true];
}

/**
 * Records Bitmap scaling events.
 *
 * Logged via Hummingbird for probes at android.graphics.Bitmap scaling methods.
 *
 * Estimated Logging Rate:
 *   Peak: 10 times in a second | Avg: O(hundreds) per device per day
 */
message AndroidGraphicsBitmapScaled {
    optional int32 uid = 1 [(is_uid) = true];
    optional int32 original_width = 2;
    optional int32 original_height = 3;
    optional int32 scaled_width = 4;
    optional int32 scaled_height = 5;
    optional AndroidGraphicsBitmapAllocationSnapshot.PixelStorageType
        pixel_storage_type = 6;
    optional string activity_name = 7;
}

/**
 * Records Runtime Permission Grants *only* when the app gaining the permission
 * had an enabled accessibility service.
 *
 * Logged via Hummingbird for probes at
 * PermissionManagerService.grantRuntimePermission and
 * Binder.execTransactInternal (for preceding a11y calls).
 *
 * Estimated Logging Rate:
 *   Peak: 10 times in a second | Avg: O(tens) per device per day
 */
message AccessibilityRuntimePermissionGrantReported {
    optional int32 uid = 1 [(is_uid) = true];
    optional string permission_name = 2;
    optional int64 timestamp_millis = 3;
    repeated int32 preceding_accessibility_service_connection_code = 4;
    repeated int64 preceding_accessibility_service_connection_timestamps_millis = 5;
}

enum UprobeStatsBpfProgram {
    UPROBE_STATS_BPF_PROGRAM_UNSPECIFIED = 0;
    PROG_ACCESSIBILITY_UPROBE_ACCESSIBILITY_SERVICE_CONNECTION = 1;
    PROG_ACCESSIBILITY_UPROBE_GRANT_RUNTIME_PERMISSION = 2;
    PROG_BINDER_UPROBE_EXEC_TRANSACT_INTERNAL = 3;
    PROG_BITMAP_ALLOCATION_OUTPUT = 4;
    PROG_BITMAP_ALLOCATION_UPROBE_ACTIVITY_PERFORM_START = 5;
    PROG_BITMAP_ALLOCATION_UPROBE_APPLY_FREE_FUNCTION = 6;
    PROG_BITMAP_ALLOCATION_UPROBE_BITMAP_CREATION_FOR_SNAPSHOT = 7;
    PROG_BITMAP_ALLOCATION_UPROBE_CREATE_SCALED_BITMAP = 8;
    PROG_DISRUPTIVE_APP_UPROBE_BIND_SERVICE_LOCKED = 9;
    PROG_DISRUPTIVE_APP_UPROBE_SET_COMPONENT_ENABLED_SETTING = 10;
    PROG_GENERIC_INSTRUMENTATION_UPROBE_CALL_DETAIL = 11;
    PROG_GENERIC_INSTRUMENTATION_UPROBE_CALL_TIMESTAMP = 12;
    PROG_KEEPALIVE_UPROBE_ACQUIRE_WAKE_LOCK_INTERNAL = 13;
    PROG_KEEPALIVE_UPROBE_RELEASE_WAKE_LOCK_INTERNAL = 14;
}

enum UprobeStatsBpfMapPath {
    UPROBE_STATS_BPF_MAP_PATH_UNSPECIFIED = 0;
    BPF_MAP_PATH_ACCESSIBILITY_OUTPUT_BUF = 1;
    BPF_MAP_PATH_BINDER_OUTPUT_BUF = 2;
    BPF_MAP_PATH_BITMAP_ALLOCATION_OUTPUT = 3;
    BPF_MAP_PATH_DISRUPTIVE_APP_BIND_SERVICE_LOCKED_OUTPUT_BUF = 4;
    BPF_MAP_PATH_DISRUPTIVE_APP_COMPONENT_ENABLED_SETTING_OUTPUT_BUF = 5;
    BPF_MAP_PATH_GENERIC_INSTRUMENTATION_CALL_DETAIL_BUF = 6;
    BPF_MAP_PATH_GENERIC_INSTRUMENTATION_CALL_TIMESTAMP_BUF = 7;
    BPF_MAP_PATH_KEEPALIVE_OUTPUT_BUF = 8;
}

/**
 * Logged by UprobeStats to report various internal errors.
 *
 * Logged from:
 * packages/modules/UprobeStats
 *
 * Estimated Logging Rate:
 * Peak: 10 times in 1 min | Avg: O(1) per device per day
 */
message UprobeStatsInternalError {
  enum ErrorType {
    ERROR_TYPE_UNSPECIFIED = 0;
    ERROR_TYPE_SERVICE_STARTUP_FAILED = 1;
    ERROR_TYPE_CONFIG_PARSE_FAILED = 2;
    ERROR_TYPE_TASK_CONFLICT = 3;
    ERROR_TYPE_TASK_EXECUTION_FAILED = 4;
    ERROR_TYPE_BINDER_FILTER_SETUP_FAILED = 5;
    ERROR_TYPE_BINDER_FILTER_CLEANUP_FAILED = 6;
    // Failed to attach a BPF probe to a target process.
    ERROR_TYPE_BPF_PROGRAM_ATTACH_FAILED = 7;
    // Failed to create a BPF ring buffer for polling.
    ERROR_TYPE_BPF_RING_BUFFER_CREATE_FAILED = 8;
    // An error occurred during the polling of a BPF ring buffer.
    ERROR_TYPE_BPF_RING_BUFFER_POLL_FAILED = 9;
    // The BPF program itself reported an error state via its output data.
    ERROR_TYPE_BPF_PROGRAM_ERROR = 10;
    // The userspace daemon received data from the BPF program, but it was malformed
    // or logically invalid (e.g. an unexpected empty string).
    ERROR_TYPE_BPF_RING_BUFFER_DATA_INVALID = 11;
  }
  optional ErrorType error_type = 1;
  optional int64 task_id = 2;
  optional UprobeStatsBpfProgram bpf_program = 3;
  optional UprobeStatsBpfMapPath map_path = 4;
  // An int discriminating where in a program/buffer the failure occurred,
  // if detectible.
  optional int64 failure_point = 5;
}

/**
 * Logged by UprobeStats for key invocation milestones.
 *
 * Logged from:
 * packages/modules/UprobeStats
 *
 * Estimated Logging Rate:
 * Peak: 1 times in 1 min | Avg: O(1) per device per day
 */
message UprobeStatsInvocation {
  enum InvocationType {
    INVOCATION_TYPE_UNSPECIFIED = 0;
    INVOCATION_TYPE_SERVICE_STARTED = 1;
    INVOCATION_TYPE_START_TASKS_RECEIVED = 2;
  }
  optional InvocationType invocation_type = 1;
}

/**
 * Logged by UprobeStats when a BPF program is successfully attached.
 *
 * Logged from:
 * packages/modules/UprobeStats
 *
 * Estimated Logging Rate:
 * Peak: 10 times in 1 min | Avg: O(tens) per device per day
 */
message UprobeStatsBpfAttached {
  // Name of the BPF program that was attached.
  optional UprobeStatsBpfProgram bpf_program = 1;
  // Fully qualified class name of the method being targeted.
  // This is hard coded in the config pushed from Google.
  // Example: "android.graphics.Bitmap"
  optional string probed_class = 2;
  // Method name of the method being targeted.
  // This is hard coded in the config pushed from Google.
  // Example: "createBitmap"
  optional string probed_method = 3;
  // Name of the process that was probed.
  // Example: "system_server"
  optional string probed_process_name = 4;
  // ID of the task that attached this probe.
  optional int64 task_id = 5;
}

/**
 * Logged by UprobeStats when a BPF map is polled.
 *
 * Logged from:
 * packages/modules/UprobeStats
 *
 * Estimated Logging Rate:
 * Peak: 10 times in 1 min | Avg: O(tens) per device per day
 */
message UprobeStatsBpfMapPolled {
  // The absolute path of the BPF map that was polled.
  // The path is determined by the BPF map definition and does not contain
  // unique identifiers (like a hash) per session.
  // Example: "/sys/fs/bpf/uprobestats/map_BitmapAllocation_active_bitmaps"
  optional UprobeStatsBpfMapPath map_path = 1;
  // Duration that we polled that map path in milliseconds.
  optional int64 poll_duration_millis = 2;
  // Total # of events that were emitted over that duration.
  optional int64 events_count = 3;
  // ID of the task that polled this map.
  optional int64 task_id = 4;
}

/**
 * Logged by UprobeStats when suspicious wakelock behavior is detected.
 *
 * Logged from:
 * packages/modules/UprobeStats
 *
 * Estimated Logging Rate:
 * Peak: 10 times in 1 min | Avg: O(tens) per device per day
 */
message SuspiciousWakelockBehaviorReported {
  enum BehaviorType {
    BEHAVIOR_TYPE_UNSPECIFIED = 0;
    BEHAVIOR_TYPE_HIGH_FREQUENCY_ACQUISITION = 1;
    BEHAVIOR_TYPE_MULTIPLE_SIMULTANEOUS_LOCKS = 2;
    BEHAVIOR_TYPE_LONG_HELD_LOCK = 3;
    BEHAVIOR_TYPE_CYCLING_WAKELOCKS = 4;
  }
  optional BehaviorType behavior_type = 1;
  // UID of the app performing the suspicious behavior.
  optional int32 uid = 2 [(is_uid) = true];
  // Wakelock flags.
  optional android.os.WakeLockLevelEnum flags = 3;
  // Wakelock tag.
  optional string tag = 4;
}
