syntax = "proto2";

package android.signature;

option java_outer_classname = "SignatureEnums";
option java_multiple_files = true;

// The type of the signature.
enum SignatureType {
  SIGNATURE_TYPE_UNKNOWN = 0;
  SIGNATURE_TYPE_DRAW = 1;
  SIGNATURE_TYPE_TYPE = 2;
  SIGNATURE_TYPE_UPLOAD = 3;
}

// The type of error encountered by the Signature Picker app.
enum SignatureAppErrorType {
  SIGNATURE_APP_ERROR_TYPE_UNKNOWN = 0;
  SIGNATURE_APP_ERROR_TYPE_DB_READ_FAILED = 1;
  SIGNATURE_APP_ERROR_TYPE_DB_WRITE_FAILED = 2;
  SIGNATURE_APP_ERROR_TYPE_PROVIDER_UUID_NOT_FOUND = 3;
  SIGNATURE_APP_ERROR_TYPE_DB_DELETE_FAILED = 4;
  SIGNATURE_APP_ERROR_TYPE_UPLOAD_FAILED = 5;
}

// The screen where a signature action occurred.
enum SignatureScreen {
  SIGNATURE_SCREEN_UNKNOWN = 0;
  SIGNATURE_SCREEN_PICKER = 1;
  SIGNATURE_SCREEN_SETTINGS = 2;
}
