/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

syntax = "proto2";

message AtomMedium {
    enum EnumMedium {
        UNKNOWN = 0;
        VALUE_1 = 1;
        VALUE_2 = 2;
        VALUE_3 = 3;
        VALUE_4 = 4;
        VALUE_5 = 5;
        VALUE_6 = 6;
        VALUE_7 = 7;
        VALUE_8 = 8;
        VALUE_9 = 9;
        VALUE_10 = 10;
    }

    optional string string_field_1 = 1;
    optional string string_field_2 = 2;
    optional string string_field_3 = 3;
    optional string string_field_4 = 4;
    optional string string_field_5 = 5;
    optional int32 int32_field_1 = 6;
    optional int32 int32_field_2 = 7;
    optional int32 int32_field_3 = 8;
    optional int32 int32_field_4 = 9;
    optional int32 int32_field_5 = 10;
    optional int32 int32_field_6 = 11;
    optional int32 int32_field_7 = 12;
    optional int32 int32_field_8 = 13;
    optional int32 int32_field_9 = 14;
    optional int32 int32_field_10 = 15;
    optional int64 int64_field_1 = 16;
    optional int64 int64_field_2 = 17;
    optional int64 int64_field_3 = 18;
    optional int64 int64_field_4 = 19;
    optional int64 int64_field_5 = 20;
    optional int64 int64_field_6 = 21;
    optional int64 int64_field_7 = 22;
    optional int64 int64_field_8 = 23;
    optional int64 int64_field_9 = 24;
    optional int64 int64_field_10 = 25;
    optional bool bool_field_1 = 26;
    optional bool bool_field_2 = 27;
    optional bool bool_field_3 = 28;
    optional bool bool_field_4 = 29;
    optional bool bool_field_5 = 30;
    optional float float_field_1 = 31;
    optional float float_field_2 = 32;
    optional float float_field_3 = 33;
    optional float float_field_4 = 34;
    optional float float_field_5 = 35;
    optional EnumMedium enum_field_1 = 36;
    optional EnumMedium enum_field_2 = 37;
    optional EnumMedium enum_field_3 = 38;
    optional EnumMedium enum_field_4 = 39;
    optional EnumMedium enum_field_5 = 40;
}
