/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

syntax = "proto2";

package android.os.statsd.location;

import "frameworks/proto_logging/stats/atoms.proto";
import "frameworks/proto_logging/stats/atom_field_options.proto";
import "frameworks/proto_logging/stats/enums/contexthub/enums.proto";

option java_package = "com.android.os.location";
option java_multiple_files = true;

extend Atom {
  optional EmergencyStateChanged emergency_state_changed = 633
      [(module_name) = "framework"];

  optional ChreSignificantMotionStateChanged
      chre_significant_motion_state_changed = 868 [(module_name) = "chre"];

  optional PopulationDensityProviderLoadingReported
      population_density_provider_loading_reported = 1002
      [(module_name) = "framework"];

  optional DensityBasedCoarseLocationsUsageReported
      density_based_coarse_locations_usage_reported = 1003
      [(module_name) = "framework"];

  optional DensityBasedCoarseLocationsProviderQueryReported
      density_based_coarse_locations_provider_query_reported = 1004
      [(module_name) = "framework"];

  optional LocationMlsViolationObserved location_mls_violation_observed = 1349
      [(module_name) = "framework"];
}

/**
 * Logs when emergency state changes
 *
 * Logged from:
 *   frameworks/base/services/core/java/com/android/server/location/LocationManagerService.java
 */
message EmergencyStateChanged {
  optional bool is_in_emergency = 1 [
     (state_field_option).exclusive_state = true,
     (state_field_option).nested = false
  ];
}

/**
 * Logs when the significant motion state changed. Motion is detected in the
 * CHRE nanoapp. Significant motion has a specific definition "a motion that
 * might lead to a change in the user location"
 */
message ChreSignificantMotionStateChanged {
  optional android.contexthub.ContextHubSignificantMotionState state = 1;
}

/**
 * Logs when the LocationManagerService finds and instantiates a
 * IPopulationDensityProvider, based on the XML configuration.
 * Logged from:
 *    frameworks/base/services/core/java/com/android/server/location/
 *    LocationManagerService.java
 * Estimated Logging Rate:
 *    Peak: 1 times in 5 min (once per boot) | Avg: ~1 per device per day
 */
message PopulationDensityProviderLoadingReported {

  // Is true if the provider isn't found, or if any error occurs when creating
  // the provider.
  optional bool provider_null = 1;

  // The latency between the framework creating the
  // ProxyPopulationDensityProvider and the Binder interface being ready.
  optional int32 provider_start_time_millis = 2;
}

/**
 * Logs when the LocationFudger uses the new density-based coarse locations.
 * Logged from:
 *    frameworks/base/services/core/java/com/android/server/location/fudger/
 *    LocationFudgerCache.java
 * Estimated Logging Rate:
 *    Peak: 1 times in 10 min (rate-limited) | Avg: ~100 per device per day
 */
message DensityBasedCoarseLocationsUsageReported {

  // If the new algo is skipped because the cache has no default.
  optional bool skipped_no_default = 1;

  // If the answer to the query was already in cache (default isn't used).
  optional bool is_cache_hit = 2;

  // Returns the default stored in the cache (used on cache miss).
  optional int32 default_coarsening_level = 3;
}

/**
 * Logs when the LocationFudger uses the new density-based coarse locations.
 * Logged from:
 *    frameworks/base/services/core/java/com/android/server/location/fudger/
 *    LocationFudgerCache.java
 * Estimated Logging Rate:
 *    Peak: 1 times in 10 min (once per S2 cell at level 12. Peak is if the
 *    device is continually changing cells, which are ~6km²).
 *    Avg: ~100 per device per day
 */
 message DensityBasedCoarseLocationsProviderQueryReported {

  // The latency between firing the query and receiving an answer.
  optional int32 query_duration_millis = 1;

  // Is true if querying the provider returned any error.
  optional bool is_error = 2;
}

/**
 * Logs when a location is delivered with MLS disabled.
 * Logged from:
 *    frameworks/base/services/core/java/com/android/server/location/injector/
 *    LocationUsageLogger.java
 * Estimated Logging Rate:
 *    Peak: 1 time in 100000 min (not rate-limited, but should be very rare)
 *    Avg: ~0.01 per device per day
 */
message LocationMlsViolationObserved {
  // The specific app operation code that was noted (e.g.,
  // AppOpsManager.OP_FINE_LOCATION).
  optional string op_code = 1;
  // The package name of the app that received the location.
  optional string package_name = 2;
  // An optional string provided by the application to further specify the
  // source of the operation within its package.
  optional string attribution_tag = 3;
  // Flags from AppOpsManager.OnNotedCallback. This is a bitmask of OP_FLAG_*
  // constants defined in AppOpsManager.OpFlags, indicating whether the
  // operation is on behalf of the app itself (OP_FLAG_SELF), or proxied by a
  // trusted (OP_FLAG_TRUSTED_PROXY) or untrusted (OP_FLAG_UNTRUSTED_PROXY) app,
  // or blamed on the app by a trusted (OP_FLAG_TRUSTED_PROXIED) or untrusted
  // (OP_FLAG_UNTRUSTED_PROXIED) app. See {@link
  // android.app.AppOpsManager.OpFlags} for more details.
  optional int32 app_ops_flags = 4;
  // Result from AppOpsManager.OnNotedCallback. This is one of the MODE_*
  // constants defined in AppOpsManager.Mode, indicating the result of the
  // operation. Possible values include MODE_ALLOWED, MODE_IGNORED (silently
  // fail), MODE_ERRORED (fatal error), MODE_DEFAULT (use default security
  // check), and MODE_FOREGROUND (allow only when app is in foreground). See
  // {@link android.app.AppOpsManager.Mode} for more details.
  optional int32 app_ops_result = 5;
  // Whether the app was in the foreground when the location was delivered.
  optional bool is_foreground = 6;
  // The process state of the app that received the location.
  optional int32 app_process_state = 7;
  // The location permission level of the app that received the location.
  optional int32 location_permission_level = 8;
  // Whether the app has the ACCESS_FINE_LOCATION permission.
  optional bool has_fine_permission = 9;
  // Whether the app has the ACCESS_COARSE_LOCATION permission.
  optional bool has_coarse_permission = 10;
  // Whether the app has the ACCESS_BACKGROUND_LOCATION permission.
  optional bool has_background_permission = 11;
  // Whether the app has the LOCATION_BYPASS permission.
  optional bool has_location_bypass_permission = 12;
  // The grace period in milliseconds that extends before and after a location
  // app op is delivered. A violation is only logged if MLS remains disabled
  // during this entire window, which accounts for race conditions where the
  // MLS or Emergency state is toggled just before or after the delivery.
  optional int32 grace_period_millis = 13[(unit) = UNIT_MILLISECONDS];
  // Whether the location app op was noted during a grace window
  optional bool in_grace_period = 14;
}
