/*
 * Copyright (C) 2024 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

syntax = "proto2";

package android.corenetworking.platform;

option java_outer_classname = "platformProtoEnums";
option java_multiple_files = true;

enum IpType {
  IT_UNKNOWN = 0;
  IT_IPv4 = 1;
  IT_IPv6 = 2;
  IT_IPv4v6 = 3;
}

enum VpnType {
  // Consider legacy ones as unknown
  TYPE_VPN_NONE = 0;
  TYPE_VPN_SERVICE = 1;
  TYPE_VPN_PLATFORM = 2;
  TYPE_VPN_LEGACY = 3;
  TYPE_VPN_OEM = 4;
}

enum VpnProfileType {
  TYPE_UNKNOWN = 0;
  TYPE_PPTP = 1;
  TYPE_L2TP_IPSEC_PSK = 2;
  TYPE_L2TP_IPSEC_RSA = 3;
  TYPE_TYPE_IPSEC_XAUTH_PSK = 4;
  TYPE_IPSEC_XAUTH_RSA = 5;
  TYPE_IPSEC_HYBRID_RSA = 6;
  TYPE_IKEV2_IPSEC_USER_PASS = 7;
  TYPE_IKEV2_IPSEC_PSK = 8;
  TYPE_IKEV2_IPSEC_RSA = 9;
  TYPE_IKEV2_FROM_IKE_TUN_CONN_PARAMS = 10;
}
