/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

syntax = "proto2";

package android.os.statsd.media;

import "frameworks/proto_logging/stats/atoms.proto";
import "frameworks/proto_logging/stats/atom_field_options.proto";
import "frameworks/proto_logging/stats/enums/media/router/enums.proto";

option java_package = "com.android.os.media";
option java_multiple_files = true;

extend Atom {
  optional MediaRouterEventReported media_router_event_reported = 1017
      [(module) = "mediarouter"];
  optional MediaRoutingSessionTransferReported media_routing_session_transfer_reported = 1142
      [(module) = "mediarouter"];
}

/**
 * Pushed atom. Logs an event for media router.
 *
 * Logged from:
 *   frameworks/base/media/java/android/media/
 * Estimated Logging Rate:
 *   Avg: 10 per device per day
 */
message MediaRouterEventReported {
  optional android.media.router.EventType event_type = 1;
  optional android.media.router.Result result = 2;
}

/**
 * Pushed atom. Logs an event for a media routing session when it is being transferred.
 *
 * Logged from:
 *   frameworks/base/media/java/android/media/
 * Estimated Logging Rate:
 *   Avg: 10 per device per day
 */
message MediaRoutingSessionTransferReported {
  // Point where the routing session originated from (Output switcher, Unified Media Object notification card, etc.)
  optional android.media.router.EntryPoint entry_point = 1;
  // Client app package uid for which the media is being routed.
  optional int32 client_package_uid = 2 [(is_uid) = true];
  // Whether the session routes media to system routes (BUILT_IN_SPEAKERS, BT Devices, etc.)
  optional bool is_system_session = 3;
  // The reason for the session being transferred.
  optional android.media.router.TransferReason transfer_reason = 4;
  // Whether the device where media is being routed was an intelligent device suggestion.
  optional bool is_suggested_device = 5;
  // Length of the media routing session in millis.
  optional int64 session_length_millis = 6;
}
